POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Ni",
    "number": "032-434213"
}
###
PUT http://localhost:3001/api/persons/60d854b973b6722c84dafb25 HTTP/1.1
Content-Type: application/json

{
  "name":"Nima Shadab",
  "number": "201242134235"
}
// testing framework
###
GET http://localhost:3001/api/persons/60d854b973b6722c84dafb25 HTTP/1.1